// هذ لملف مخصص فقط لتخزين لمنتجت. لأسعر هن بلدولر (لسعر لأصلي للمورد)
// لموقع سيقوم تلقئيً بإضفة 20% وتحويله لـ 44 أو 650.

export const importedProducts = [
{ id: 1,  name: { fr: "GUEETON Souris sans fil ultra-mince 2.4G Bluetooth double mode rechargeable argent" },  originalPriceCFA: 3000, image: " https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/64/68849/1.jpg?1126 ", }, 
{ id: 2,  name: { fr: "GUEETON 128 Go Clé USB OTG Stylo à bille NOIR avec 4 recharges de rechange" },  originalPriceCFA: 4000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/48/21489/1.jpg?4214", },
{ id: 3,  name: { fr: "Station D'accueil 8 En 2 Avec Adaptateur Multiport USB Type-C" },  originalPriceCFA: 8000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/89/602621/1.jpg?4131", },
{ id: 4,  name: { fr: "Kingnote Souris de jeu filaire optique et électrique, nécessaire pour voyage d'affaires, DPI réglable à 3 vitesses" },  originalPriceCFA: 2500, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/23/883621/3.jpg?6724", },
{ id: 5,  name: { fr: "LM-Ensemble sac à dos 3 en 1 pour ordinateur portable - Noir" },  originalPriceCFA: 6000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/80/583621/1.jpg?5763", },
{ id: 6,  name: { fr: "Sac à main multifonctionnel 5 en 1 à la mode pour femmes - Noir" },  originalPriceCFA: 6000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/98/768221/1.jpg?6081", },
{ id: 7,  name: { fr: "Lenovo IdeaPad 1 - 8Go Ram 256Go SSD Dual Core Ecran 15.6 + Sac et Clé Usb 64Go et Souris" },  originalPriceCFA: 190000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/62/956621/1.jpg?8108", },
{ id: 8,  name: { fr: "Day By Day Men Gamme Vanity Les Indispensables - Homme - 6pcs" },  originalPriceCFA: 7000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/88/502601/1.jpg?4788", },
{ id: 9,  name: { fr: "TOUPHY Tondeuse A Cheveux Electrique Rechargeable" },  originalPriceCFA: 8000, image: "https://sn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/74/651321/1.jpg?3959", },
{ id: 10,  name: { fr: "TOUPHY 2Piece / Set professionnel tondeuse à cheveux T-Blade Trimmer Set pour hommes" },  originalPriceCFA: 7000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/11/736621/1.jpg?3919", },
{ id: 11,  name: { fr: "Guixia Écouteurs Intra-Auriculaires Bluetooth Transparent À Réduction De Bruit Guixia Air31" },  originalPriceCFA: 3000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/58/653221/1.jpg?8427", },
{ id: 12,  name: { fr: "TiLECC TiLECC Bluetooth Air PRO3 Casque sans fil HIFI Écouteurs à la mode" },  originalPriceCFA: 4000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/34/880121/1.jpg?2211", },
{ id: 13,  name: { fr: "Dell e7470 Core I7 14 pouces, 8Go, 256Go +sac" },  originalPriceCFA: 165000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/83/952821/1.jpg?7636", },
{ id: 14,  name: { fr: "TWS Air Ear pod pro 2 Air 5 avec languette écouteur Bluetooth tactile ultra Bass 2e gen - blanc" },  originalPriceCFA: 5000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/38/253721/1.jpg?5492", },
{ id: 15,  name: { fr: "GALUIN Chaussures de football pour jeunes avec crampons professionnels respirants pour hommes - Bleu" },  originalPriceCFA: 9000, image: "https://sn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/04/725421/1.jpg?1148", },
{ id: 16,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 17,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 18,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 19,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 20,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 21,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 22,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 23,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 24,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 25,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 26,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 27,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 28,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 29,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 30,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 31,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 32,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 33,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 34,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 35,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 36,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 37,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 38,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 39,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 40,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 41,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 42,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 43,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 44,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },
{ id: 45,  name: { fr: " " },  originalPriceCFA: 0, image: " ", },

];